In [6]:
import numpy as np

In [17]:
l = [1,2,3,4,5]

In [18]:
arr = np.array(l)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr.shape

(5,)

In [14]:
M = np.array([[1,2],[3,4]])

In [15]:
M

array([[1, 2],
       [3, 4]])

In [16]:
M.shape

(2, 2)

In [25]:
def f(x):
    return x * x

print(arr)
out = f(arr)
out

[1 2 3 4 5]


array([ 1,  4,  9, 16, 25])

In [26]:
M

array([[1, 2],
       [3, 4]])

In [27]:
M.T

array([[1, 3],
       [2, 4]])

In [28]:
# matrix multiplication
M @ M.T

array([[ 5, 11],
       [11, 25]])

In [33]:
a = np.random.uniform(0, 1, 10)
a

array([0.59382275, 0.91030669, 0.92439289, 0.23060261, 0.34226954,
       0.66843957, 0.98744733, 0.72385766, 0.24141918, 0.54882949])

In [37]:
a = np.random.normal(1, 5, 20)
a

array([ 1.87720678,  2.24169905,  1.55322164, -1.96233769,  9.29962763,
        1.95106893, -3.98260809, -4.84036688,  5.84287668,  6.56241986,
        9.64725673,  4.91458347,  5.12484766, -4.35321575,  0.03955063,
        4.7501215 ,  5.54022289,  4.4219991 ,  4.14393396,  0.1187313 ])

In [46]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [48]:
S = M.T @ M

In [49]:
np.linalg.eig(S)

(array([ 0.13393125, 29.86606875]),
 array([[-0.81741556, -0.57604844],
        [ 0.57604844, -0.81741556]]))

In [51]:
arr
for i in arr:
    print(i)

1
2
3
4
5


In [52]:
import pandas as pd

In [61]:
df = pd.DataFrame([1,2,3,4,5],
                  columns=["a"])
df["b"] = np.random.randint(0, 10, 5)

In [62]:
df

a  b
0  1  8
1  2  2
2  3  8
3  4  6
4  5  1

In [70]:
df["c"] = df["a"] + df["b"]

In [71]:
df

a  b   c
0  1  8   9
1  2  2   4
2  3  8  11
3  4  6  10
4  5  1   6

In [74]:
df["d"] = df["a"].apply(lambda x: x**2)
df

a  b   c   d
0  1  8   9   1
1  2  2   4   4
2  3  8  11   9
3  4  6  10  16
4  5  1   6  25

In [77]:
print(df)
df.to_numpy()

   a  b   c   d
0  1  8   9   1
1  2  2   4   4
2  3  8  11   9
3  4  6  10  16
4  5  1   6  25


array([[ 1,  8,  9,  1],
       [ 2,  2,  4,  4],
       [ 3,  8, 11,  9],
       [ 4,  6, 10, 16],
       [ 5,  1,  6, 25]], dtype=int64)

In [80]:
df = pd.read_csv("BTCUSDT-trades-2023-11-08/BTCUSDT-trades-2023-11-08.csv")
df

id    price    qty   quote_qty           time  is_buyer_maker
0        4266923342  35406.5  0.012    424.8780  1699401604617           False
1        4266923343  35406.4  0.008    283.2512  1699401604646            True
2        4266923344  35406.4  0.006    212.4384  1699401604652            True
3        4266923345  35406.4  0.004    141.6256  1699401604652            True
4        4266923346  35406.4  0.150   5310.9600  1699401604652            True
...             ...      ...    ...         ...            ...             ...
3098476  4270021841  35626.7  0.257   9156.0619  1699487999808            True
3098477  4270021842  35626.6  0.673  23976.7018  1699487999808            True
3098478  4270021843  35626.6  0.023    819.4118  1699487999808            True
3098479  4270021844  35626.7  0.014    498.7738  1699487999902           False
3098480  4270021845  35626.7  0.006    213.7602  1699487999936           False

[3098481 rows x 6 columns]

In [83]:
df.head(10)

id    price    qty  quote_qty           time  is_buyer_maker
0  4266923342  35406.5  0.012   424.8780  1699401604617           False
1  4266923343  35406.4  0.008   283.2512  1699401604646            True
2  4266923344  35406.4  0.006   212.4384  1699401604652            True
3  4266923345  35406.4  0.004   141.6256  1699401604652            True
4  4266923346  35406.4  0.150  5310.9600  1699401604652            True
5  4266923347  35406.4  0.013   460.2832  1699401604652            True
6  4266923348  35406.4  0.011   389.4704  1699401604652            True
7  4266923349  35406.4  0.003   106.2192  1699401604652            True
8  4266923350  35406.4  0.004   141.6256  1699401604652            True
9  4266923351  35406.3  0.084  2974.1292  1699401604652            True

In [84]:
df.describe()

id         price           qty     quote_qty          time
count  3.098481e+06  3.098481e+06  3.098481e+06  3.098481e+06  3.098481e+06
mean   4.268473e+09  3.551901e+04  1.080463e-01  3.840396e+03  1.699459e+12
std    8.944609e+05  2.285112e+02  4.871870e-01  1.734287e+04  2.456579e+07
min    4.266923e+09  3.507300e+04  1.000000e-03  3.507320e+01  1.699402e+12
25%    4.267698e+09  3.532440e+04  3.000000e-03  1.076193e+02  1.699441e+12
50%    4.268473e+09  3.544450e+04  1.100000e-02  3.882626e+02  1.699467e+12
75%    4.269247e+09  3.572370e+04  6.500000e-02  2.296970e+03  1.699479e+12
max    4.270022e+09  3.615000e+04  2.307430e+02  8.232910e+06  1.699488e+12

In [89]:
df["normalized_price"] = (df["price"] - df["price"].mean()) / df["price"].std()

In [90]:
df.head(20)

id    price    qty  quote_qty           time  is_buyer_maker  \
0   4266923342  35406.5  0.012   424.8780  1699401604617           False   
1   4266923343  35406.4  0.008   283.2512  1699401604646            True   
2   4266923344  35406.4  0.006   212.4384  1699401604652            True   
3   4266923345  35406.4  0.004   141.6256  1699401604652            True   
4   4266923346  35406.4  0.150  5310.9600  1699401604652            True   
5   4266923347  35406.4  0.013   460.2832  1699401604652            True   
6   4266923348  35406.4  0.011   389.4704  1699401604652            True   
7   4266923349  35406.4  0.003   106.2192  1699401604652            True   
8   4266923350  35406.4  0.004   141.6256  1699401604652            True   
9   4266923351  35406.3  0.084  2974.1292  1699401604652            True   
10  4266923352  35406.3  0.112  3965.5056  1699401604652            True   
11  4266923353  35406.3  0.141  4992.2883  1699401604652            True   
12  4266923354  35406.3  0.017   601.9071  1699401604652            True   
13  4266923355  35406.3  0.021   743.5323  1699401604652            True   
14  4266923356  35406.3  0.021   743.5323  1699401604652            True   
15  4266923357  35406.3  0.112  3965.5056  1699401604652            True   
16  4266923358  35406.3  0.026   920.5638  1699401604652            True   
17  4266923359  35406.3  0.017   601.9071  1699401604652            True   
18  4266923360  35406.3  0.003   106.2189  1699401604652            True   
19  4266923361  35406.2  0.003   106.2186  1699401604652            True   

    normalized_price  
0          -0.492341  
1          -0.492779  
2          -0.492779  
3          -0.492779  
4          -0.492779  
5          -0.492779  
6          -0.492779  
7          -0.492779  
8          -0.492779  
9          -0.493216  
10         -0.493216  
11         -0.493216  
12         -0.493216  
13         -0.493216  
14         -0.493216  
15         -0.493216  
16         -0.493216  
17         -0.493216  
18         -0.493216  
19         -0.493654

In [95]:
df1 = pd.DataFrame()
df1["a"] = [1,2]
df1["b"] = [34, 75]
df1

a   b
0  1  34
1  2  75

In [96]:
df2 = pd.DataFrame()
df2["a"] = [1,2,3,4]
df2["b"] = ["bla", "hello", "python", "adrien"]
df2

a       b
0  1     bla
1  2   hello
2  3  python
3  4  adrien

In [97]:
df = pd.merge(df1, df2, on="a", how="inner")
df

a  b_x    b_y
0  1   34    bla
1  2   75  hello

In [101]:
df = df.rename({"b_x": "b", "b_y": "c"}, axis=1)
df

a   b      c
0  1  34    bla
1  2  75  hello